# 定义基础镜像
FROM docker.elastic.co/apm/apm-server:7.1.0
# 定义维护者信息
LABEL maintainer="zhu.yuehao@iwhalecloud.com"

COPY apm-server.yml /usr/share/apm-server/apm-server.yml
USER root
RUN chown root:apm-server /usr/share/apm-server/apm-server.yml
USER apm-server
