# 定义基础镜像
FROM docker.elastic.co/elasticsearch/elasticsearch:7.1.0
# 定义维护者信息
LABEL maintainer="zhu.yuehao@iwhalecloud.com"
# 设置容器时区为中国时区
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 生成证书
RUN bin/elasticsearch-certutil cert -out config/elastic-certificates.p12 -pass ""

